"""The CreationInfo CSV - Siemens' template-fill delivery surface, as the system's "csv" emitter.

Chapter: how a built block reaches TIA when it ships as data rather than ready code. Each block
becomes `CreationInfo/<name>.csv` in the `$/#/%/@` layout the OP importer fills into the block's
template XML: `$` names the template (a RELATIVE `Templates/<file>.xml` - the folder is
self-contained, an absolute PL path is dead on the OP machine), `#` is a comment, `%` the header
(placeholders wrapped `!!key$$`), `@` one row per network - a LIST cell spreads horizontally (the
ITERATOR). The block's template XML is COPIED into `Templates/` beside the CSVs.

Where you meet it in the app: the 800 phase log's "CreationInfo CSV" surface lines; the files under
BuilderData/SoftwareBlocks/CreationInfo. Registered as `SYSTEM.emitters["csv"]` - the build engine
routes every non-ready block here and never knows the format (PL4 coupling #2/#6, resolved).
"""
from __future__ import annotations

import csv
import os
import shutil


def _wrap(col: str) -> str:
    """% / @ header form: TemplateType + #meta columns unwrapped; placeholders are !!key$$."""
    return col if (col == "TemplateType" or col.startswith("#")) else f"!!{col}$$"


def _ordered_columns(canonical_keys, table) -> list:
    """The template's full key set first (TemplateType leading), then any extra builder columns; list
    (ITERATOR) columns moved last."""
    cols = list(canonical_keys)
    for c in table.columns:
        if c not in cols:
            cols.append(c)

    def is_iter(c):
        return any(isinstance(r.get(c), (list, tuple)) for r in table.rows)
    iters = [c for c in cols if c != "TemplateType" and is_iter(c)]
    scal = [c for c in cols if c != "TemplateType" and c not in iters]
    head = ["TemplateType"] if "TemplateType" in cols else []
    return head + scal + iters


def _at_row_cells(row, ordered) -> list:
    """The @-row cells for `ordered` columns: scalars as-is, a list value spread across cells (the
    horizontal ITERATOR)."""
    cells = []
    for c in ordered:
        v = row.get(c, "")
        if isinstance(v, (list, tuple)):
            cells.extend("" if x is None else str(x) for x in v)
        else:
            cells.append("" if v is None else str(v))
    return cells


def ship_template(template_ref: str, tpl_dir: str) -> str:
    """Copy a CSV-emitting block's template XML into `<creation_dir>/Templates/` and return the
    RELATIVE reference written into the CSV (`Templates/<file>.xml`, forward slash -
    machine-independent). A missing source ships nothing but still writes the relative ref (the OP
    import reports it, exactly like the old dangling absolute path did)."""
    base = os.path.basename(str(template_ref or ""))
    if not base:
        return ""
    if os.path.exists(template_ref):
        os.makedirs(tpl_dir, exist_ok=True)
        shutil.copyfile(template_ref, os.path.join(tpl_dir, base))
    return f"Templates/{base}"


def write_creation_csv(creation_dir: str, name: str, template_ref: str, table, canonical_keys) -> str:
    """Serialize one reconstructed Table to CreationInfo/<name>.csv in the $/#/%/@ layout, with the %
    header = the template's full key set (canonical_keys) + any extra builder columns."""
    ordered = _ordered_columns(canonical_keys, table)
    path = os.path.join(creation_dir, f"{name}.csv")
    os.makedirs(creation_dir, exist_ok=True)
    with open(path, "w", newline="", encoding="utf-8") as f:
        w = csv.writer(f)
        w.writerow(["$", f"template={template_ref}"])
        w.writerow(["#", "generated by pipeline5 (phase 800)"])
        w.writerow(["%"] + [_wrap(c) for c in ordered])
        for r in table.rows:
            w.writerow(["@"] + _at_row_cells(r, ordered))
    return path


def write(block, table, ctx) -> str:
    """The SYSTEM.emitters["csv"] entry: ship the block's template into `<out_dir>/Templates/`, write
    the CSV with the relative reference, return the CSV path. `ctx`: {"out_dir", "tpl_dir"}."""
    rel_ref = ship_template(block["template_ref"], ctx["tpl_dir"])
    return write_creation_csv(ctx["out_dir"], block["name"], rel_ref, table, block["keys"])
