"""Phase 800a (Software Generation) - the builder spine (Table/Database/registry), the $/#/%/@ CreationInfo
serialization (the !!key$$ wrap + the horizontal ITERATOR spread), the simple builders (00/06/07), and the
build->project SSOT round-trip. Pure + data-independent (the real-doc CSV parity is a separate script)."""
import os
import tempfile

from _harness import run, eq, ok
from pipeline4.core.database import Database as DB
from pipeline4.domain.blocks import engine
from pipeline4.domain.blocks.database import Database
from pipeline4.domain.blocks.table import Table
from pipeline4.domain.blocks import builders


# --- Table + Database -------------------------------------------------------------------------- #
def test_table_add_tracks_columns_and_iterator():
    t = Table("X")
    t.add(template_type="01", A="a", ITER=["x", "y"])
    t.add(template_type="02", A="b", B="c")
    eq(t.columns, ["TemplateType", "A", "ITER", "B"], "columns in first-seen order")
    eq(len(t), 2)
    eq(t.rows[0]["ITER"], ["x", "y"], "a list cell is kept as the ITERATOR")


def test_database_list_cell_filters():
    rows = [{"script_type": "KQ", "datablocks": ["03_FDBACK", "03_FDBACK_RAW"], "matrix_areas": ["AREA 1"]},
            {"script_type": "ki", "datablocks": [], "matrix_areas": ["AREA 1", "AREA 2"]},
            {"script_type": "KQ", "datablocks": "03_FDBACK|X", "matrix_areas": ""}]   # tolerate a legacy string
    db = Database(rows)
    eq(len(db.by_type("KQ")), 2, "by_type case-insensitive")
    eq(len(db.by_type("KI")), 1)
    eq(len(db.by_db("03_FDBACK")), 2, "by_db reads the JSON list cell (+ tolerates a |-string)")
    eq(len(db.by_area("AREA 2")), 1, "by_area reads the matrix_areas list cell")
    eq(db.areas(), ["AREA 1", "AREA 2"], "distinct areas, first-seen order")


# --- the $/#/%/@ serialization ----------------------------------------------------------------- #
def test_serialization_wrap_order_and_iterator():
    eq(engine._wrap("TemplateType"), "TemplateType", "TemplateType unwrapped")
    eq(engine._wrap("#meta"), "#meta", "a #meta column unwrapped")
    eq(engine._wrap("NetworkComment"), "!!NetworkComment$$", "a placeholder wrapped")
    t = Table("B")
    t.add(template_type="01", NetworkComment="hi", ITER=["a", "b", "c"])
    ordered = engine._ordered_columns(["TemplateType", "NetworkComment"], t)
    eq(ordered, ["TemplateType", "NetworkComment", "ITER"], "inventory first, the ITERATOR last")
    eq(engine._at_row_cells(t.rows[0], ordered), ["01", "hi", "a", "b", "c"], "the list spreads across cells")


def test_write_creation_csv_layout():
    with tempfile.TemporaryDirectory() as d:
        t = Table("00_X")
        t.add(template_type="01", NetworkComment="n1", ITER=["a", "b"])
        engine._write_creation_csv(d, "00_X", "C:/tpl/00_X.xml", t, ["TemplateType", "NetworkComment"])
        raw = open(os.path.join(d, "00_X.csv"), "rb").read()
        ok(not raw.startswith(b"\xef\xbb\xbf"), "no BOM")
        text = raw.decode("utf-8")
        lines = text.splitlines()
        eq(lines[0], "$,template=C:/tpl/00_X.xml", "the $ template line")
        eq(lines[1], "#,generated by pipeline4 (phase 800)", "the # comment line")
        eq(lines[2], "%,TemplateType,!!NetworkComment$$,!!ITER$$", "the % header: TemplateType + wrapped keys")
        eq(lines[3], "@,01,n1,a,b", "the @ row: TemplateType + scalar + the ITERATOR spread")


# --- the simple builders (00/06/07) ------------------------------------------------------------ #
def _node(name, ip, **kw):
    return {"profinet_name": name, "profinet_ip": ip, "I_startByte": kw.get("i0", ""), "I_endByte": kw.get("i1", ""),
            "Q_startByte": kw.get("q0", ""), "Q_endByte": kw.get("q1", ""), "name_in_db": kw.get("name_in_db", ""),
            "script_type": kw.get("script_type", "PA"), "bit": ""}


def test_builder_00_commissioning():
    rows = [_node("n1", "1.2.3.4", name_in_db="n1 1.2.3.4"),
            _node("n2", "1.2.3.5", name_in_db=""),                       # no name_in_db -> skipped
            {"profinet_name": "", "name_in_db": "x"}]                    # no profinet_name -> skipped
    t = builders.build_00_commissioning(Database(rows))
    eq(len(t), 1, "only the node with a name_in_db")
    eq(t.rows[0]["00_Commissioning.{db_element}"], "n1 1.2.3.4")
    eq(t.rows[0]["NetworkComment"], "n1 1.2.3.4")


def test_builder_06_feedback_error_chunks_to_8():
    node = _node("n1", "1.2.3.4", i0="0", i1="20", q0="0", q1="20")
    kqs = [{"script_type": "KQ", "bit": f"Q{b}.0", "name_in_db": f"KQ{b}"} for b in range(10)]   # 10 KQ on the node
    t = builders.build_06_feedback_error(Database([node] + kqs))
    eq(len(t), 2, "10 KQ -> 2 chunks of 8")
    eq(t.rows[0]["instanceOf-03_FDBACK error"], "FDBK_ERR_n1_1")
    eq(len(t.rows[0]["ITERATOR_STRINGS"]), 8, "the iterator is padded to 8")
    eq(t.rows[0]["ITERATOR_STRINGS"][:2], ["KQ0", "KQ1"])
    eq(t.rows[1]["ITERATOR_STRINGS"], ["KQ8", "KQ9"] + [builders.PAD] * 6, "the 2nd chunk padded with No Operation")


def test_builder_07_speed_control_pairs_encoders():
    rows = [{"script_type": "N1/2", "index": "1", "name_in_db": "enc1", "name_in_tagtable": "ENC1_tag", "iol_FLD": "S1"},
            {"script_type": "N2/2", "index": "1", "name_in_db": "enc2", "name_in_tagtable": "ENC2_tag"},
            {"script_type": "N1/2", "index": "2", "name_in_db": "enc3", "name_in_tagtable": "ENC3_tag", "iol_FLD": "S2"}]
    t = builders.build_07_speed_control(Database(rows))
    eq(len(t), 2, "two N1/2 indices")
    eq(t.rows[0]["instanceOf-01_Speed_Control_SLS"], "SLS_SORTER_01", "zero-padded index")
    eq(t.rows[0]["04_SPEED.{db_element:ENC2/2}"], "enc2", "the paired N2/2")
    eq(t.rows[0]["04_SPEED.{db_element:ENC}"], "Safety Encoder Failure [ S1 ]")
    eq(t.rows[1]["04_SPEED.{db_element:ENC2/2}"], "", "no N2/2 for index 2 -> blank")


# --- build -> project round-trip (the SSOT tables -> CSV) -------------------------------------- #
def test_project_reconstructs_from_tables():
    blk, mem = engine.software_blocks_table(), engine.software_block_members_table()
    blk.add(name="00_X", template_stem="TEMPLATE--v1.0--00_X", template_ref="C:/tpl/00_X.xml",
            keys=["TemplateType", "NetworkComment"], columns=["TemplateType", "NetworkComment", "ITER"])
    mem.add(block="00_X", seq=0, values={"TemplateType": "01", "NetworkComment": "n1", "ITER": ["a", "b"]})
    mem.add(block="00_X", seq=1, values={"TemplateType": "01", "NetworkComment": "n2", "ITER": ["c"]})
    with tempfile.TemporaryDirectory() as d:
        res = engine.project(DB([blk, mem]), out_dir=d)
        eq((res["count"], res["findings"]), (1, []), "one CSV, pure projection")
        lines = open(res["files"][0], encoding="utf-8").read().splitlines()
        eq(lines[2], "%,TemplateType,!!NetworkComment$$,!!ITER$$")
        eq(lines[3], "@,01,n1,a,b")
        eq(lines[4], "@,01,n2,c", "rows projected in seq order, the ITERATOR spread preserved")


if __name__ == "__main__":
    import sys
    sys.exit(run("blocks", [
        ("table_add_tracks_columns_and_iterator", test_table_add_tracks_columns_and_iterator),
        ("database_list_cell_filters", test_database_list_cell_filters),
        ("serialization_wrap_order_and_iterator", test_serialization_wrap_order_and_iterator),
        ("write_creation_csv_layout", test_write_creation_csv_layout),
        ("builder_00_commissioning", test_builder_00_commissioning),
        ("builder_06_feedback_error_chunks_to_8", test_builder_06_feedback_error_chunks_to_8),
        ("builder_07_speed_control_pairs_encoders", test_builder_07_speed_control_pairs_encoders),
        ("project_reconstructs_from_tables", test_project_reconstructs_from_tables),
    ]))
