"""Phase 800a (Software Generation) - the builder spine (Table/Database/registry), the $/#/%/@ CreationInfo
serialization (the !!key$$ wrap + the horizontal ITERATOR spread), the simple builders (00/06/07), and the
build->project SSOT round-trip. Pure + data-independent (the real-doc CSV parity is a separate script)."""
import os
import tempfile

from _harness import run, eq, ok
from pipeline4.core.database import Database as DB
from pipeline4.domain.blocks import engine, xml_emit
from pipeline4.domain.blocks.database import Database
from pipeline4.domain.blocks.table import Table
from pipeline4.domain.blocks import builders
from pipeline4.domain.db_members import instance_dbs_table


# --- Table + Database -------------------------------------------------------------------------- #
def test_table_add_tracks_columns_and_iterator():
    t = Table("X")
    t.add(template_type="01", A="a", ITER=["x", "y"])
    t.add(template_type="02", A="b", B="c")
    eq(t.columns, ["TemplateType", "A", "ITER", "B"], "columns in first-seen order")
    eq(len(t), 2)
    eq(t.rows[0]["ITER"], ["x", "y"], "a list cell is kept as the ITERATOR")


def test_database_list_cell_filters():
    rows = [{"script_type": "KQ", "datablocks": ["03_FDBACK", "03_FDBACK_RAW"], "matrix_areas": ["AREA 1"]},
            {"script_type": "ki", "datablocks": [], "matrix_areas": ["AREA 1", "AREA 2"]},
            {"script_type": "KQ", "datablocks": "03_FDBACK|X", "matrix_areas": ""}]   # tolerate a legacy string
    db = Database(rows)
    eq(len(db.by_type("KQ")), 2, "by_type case-insensitive")
    eq(len(db.by_type("KI")), 1)
    eq(len(db.by_db("03_FDBACK")), 2, "by_db reads the JSON list cell (+ tolerates a |-string)")
    eq(len(db.by_area("AREA 2")), 1, "by_area reads the matrix_areas list cell")
    eq(db.areas(), ["AREA 1", "AREA 2"], "distinct areas, first-seen order")


# --- the $/#/%/@ serialization ----------------------------------------------------------------- #
def test_serialization_wrap_order_and_iterator():
    eq(engine._wrap("TemplateType"), "TemplateType", "TemplateType unwrapped")
    eq(engine._wrap("#meta"), "#meta", "a #meta column unwrapped")
    eq(engine._wrap("NetworkComment"), "!!NetworkComment$$", "a placeholder wrapped")
    t = Table("B")
    t.add(template_type="01", NetworkComment="hi", ITER=["a", "b", "c"])
    ordered = engine._ordered_columns(["TemplateType", "NetworkComment"], t)
    eq(ordered, ["TemplateType", "NetworkComment", "ITER"], "inventory first, the ITERATOR last")
    eq(engine._at_row_cells(t.rows[0], ordered), ["01", "hi", "a", "b", "c"], "the list spreads across cells")


def test_write_creation_csv_layout():
    with tempfile.TemporaryDirectory() as d:
        t = Table("00_X")
        t.add(template_type="01", NetworkComment="n1", ITER=["a", "b"])
        engine._write_creation_csv(d, "00_X", "C:/tpl/00_X.xml", t, ["TemplateType", "NetworkComment"])
        raw = open(os.path.join(d, "00_X.csv"), "rb").read()
        ok(not raw.startswith(b"\xef\xbb\xbf"), "no BOM")
        text = raw.decode("utf-8")
        lines = text.splitlines()
        eq(lines[0], "$,template=C:/tpl/00_X.xml", "the $ template line")
        eq(lines[1], "#,generated by pipeline4 (phase 800)", "the # comment line")
        eq(lines[2], "%,TemplateType,!!NetworkComment$$,!!ITER$$", "the % header: TemplateType + wrapped keys")
        eq(lines[3], "@,01,n1,a,b", "the @ row: TemplateType + scalar + the ITERATOR spread")


# --- the simple builders (00/06/07) ------------------------------------------------------------ #
def _node(name, ip, **kw):
    return {"profinet_name": name, "profinet_ip": ip, "I_startByte": kw.get("i0", ""), "I_endByte": kw.get("i1", ""),
            "Q_startByte": kw.get("q0", ""), "Q_endByte": kw.get("q1", ""), "name_in_db": kw.get("name_in_db", ""),
            "script_type": kw.get("script_type", "PA"), "bit": ""}


def test_builder_00_commissioning():
    rows = [_node("n1", "1.2.3.4", name_in_db="n1 1.2.3.4"),
            _node("n2", "1.2.3.5", name_in_db=""),                       # no name_in_db -> skipped
            {"profinet_name": "", "name_in_db": "x"}]                    # no profinet_name -> skipped
    t = builders.build_00_commissioning(Database(rows))
    eq(len(t), 1, "only the node with a name_in_db")
    eq(t.rows[0]["00_Commissioning.{db_element}"], "n1 1.2.3.4")
    eq(t.rows[0]["NetworkComment"], "n1 1.2.3.4")


def test_builder_06_feedback_error_chunks_to_8():
    node = _node("n1", "1.2.3.4", i0="0", i1="20", q0="0", q1="20")
    kqs = [{"script_type": "KQ", "bit": f"Q{b}.0", "name_in_db": f"KQ{b}"} for b in range(10)]   # 10 KQ on the node
    t = builders.build_06_feedback_error(Database([node] + kqs))
    eq(len(t), 2, "10 KQ -> 2 chunks of 8")
    eq(t.rows[0]["instanceOf-03_FDBACK error"], "FDBK_ERR_n1_1")
    eq(len(t.rows[0]["ITERATOR_STRINGS"]), 8, "the iterator is padded to 8")
    eq(t.rows[0]["ITERATOR_STRINGS"][:2], ["KQ0", "KQ1"])
    eq(t.rows[1]["ITERATOR_STRINGS"], ["KQ8", "KQ9"] + [builders.PAD] * 6, "the 2nd chunk padded with No Operation")


def test_builder_07_speed_control_pairs_encoders():
    rows = [{"script_type": "N1/2", "index": "1", "name_in_db": "enc1", "name_in_tagtable": "ENC1_tag", "iol_FLD": "S1"},
            {"script_type": "N2/2", "index": "1", "name_in_db": "enc2", "name_in_tagtable": "ENC2_tag"},
            {"script_type": "N1/2", "index": "2", "name_in_db": "enc3", "name_in_tagtable": "ENC3_tag", "iol_FLD": "S2"}]
    t = builders.build_07_speed_control(Database(rows))
    eq(len(t), 2, "two N1/2 indices")
    eq(t.rows[0]["instanceOf-01_Speed_Control_SLS"], "SLS_SORTER_01", "zero-padded index")
    eq(t.rows[0]["04_SPEED.{db_element:ENC2/2}"], "enc2", "the paired N2/2")
    eq(t.rows[0]["04_SPEED.{db_element:ENC}"], "Safety Encoder Failure [ S1 ]")
    eq(t.rows[1]["04_SPEED.{db_element:ENC2/2}"], "", "no N2/2 for index 2 -> blank")


# --- the complex builders (02/03/04/05/08) ----------------------------------------------------- #
def test_builder_02_em_push_button_groups_inputs():
    node = _node("n1", "1.2.3.4", i0="0", i1="20", q0="0", q1="20")
    ins = ([{"script_type": "E1/2", "bit": f"I{b}.0", "name_in_db": f"PB{b}"} for b in range(3)]
           + [{"script_type": "B1/2", "bit": "I3.0", "name_in_db": "BRK0"}])   # 4 inputs -> 1 quartet
    t = builders.build_02_em_push_button(Database([node] + ins))
    eq(len(t), 1, "4 inputs (E1/2 + B1/2) -> one chunk of 4")
    eq(t.rows[0]["instanceOf-00_Push-Button_Input"], "EMPB_n1_1")
    quartet = ["PB0", "PB1", "PB2", "BRK0"]
    eq(t.rows[0]["ITERATOR_STRINGS"], quartet + quartet, "the padded quartet emitted twice")


def test_area_descriptions_reads_list_cells():
    rows = [{"matrix_areas": ["AREA 1", "AREA 2"], "areas_description": ["Infeed", "Outfeed"]},
            {"matrix_areas": "AREA 3", "areas_description": "Sorter"}]            # tolerate legacy strings
    eq(builders._area_descriptions(Database(rows)),
       {"AREA 1": "Infeed", "AREA 2": "Outfeed", "AREA 3": "Sorter"}, "list + legacy-string cells, first-seen")


def test_builder_03_zone_cumulative_per_area_group():
    rows = [
        {"script_type": "E1/2", "matrix_areas": ["AREA 1"], "areas_description": ["Infeed"],
         "name_in_db": "PB_A", "datablocks": ["01_Pushbutton", "X"]},
        {"script_type": "E1/2", "matrix_areas": ["AREA 1"], "areas_description": ["Infeed"],
         "name_in_db": "PB_B", "datablocks": ["01_Pushbutton"]},
        {"script_type": "KQ", "matrix_areas": ["AREA 1"], "areas_description": ["Infeed"],
         "name_in_db": "FDB_A", "datablocks": ["03_FDBACK"]},
    ]
    t = builders.build_03_zone_cumulative(Database(rows))
    eq(len(t), 2, "AREA 1 has PB + FDB groups (no breakers/doors)")
    eq(t.rows[0]["nameOfDB"], "01_Pushbutton", "the leftmost DB from the list cell")
    eq(t.rows[0]["02_COM.{db_element}"], "AREA 1 PB")
    eq(t.rows[0]["NetworkComment"], "AREA 1 PB - Infeed", "element - description")
    eq(t.rows[0]["ITERATOR_STRINGS"], ["PB_A", "PB_B"], "exact-sized member iterator, no padding")
    eq(t.rows[1]["02_COM.{db_element}"], "AREA 1 FDB")


def test_builder_04_estop_sorter_tier_and_generic():
    rows = [
        # a SORTER area with 3 doors -> tier cap 4 (TT01), padded to 4
        {"script_type": "DI1/2", "matrix_areas": ["AREA 1"], "IsSorterArea": "yes", "name_in_db": f"DOOR{n}"}
        for n in range(3)
    ] + [
        {"script_type": "B1/2", "matrix_areas": ["AREA 1"], "IsSorterArea": "yes", "name_in_db": "BRK1"},
        # a GENERIC area, no doors -> TT06
        {"script_type": "E1/2", "matrix_areas": ["AREA 2"], "name_in_db": "PB2"},
    ]
    t = builders.build_04_estop(Database(rows))
    eq(len(t), 2, "one network per area")
    s = next(r for r in t.rows if r["instanceOf-F_ESTOP1"] == "ESTOP_AREA 1")
    eq(s["TemplateType"], "01", "3 doors -> the cap-4 tier")
    eq(s["ITERATOR_STRINGS"], ["DOOR0", "DOOR1", "DOOR2", builders.PAD], "doors padded to the tier")
    eq(s["01_PushButton.SafetyBreaker1"], "BRK1")
    eq(s["01_PushButton.SafetyBreaker2"], "Always TRUE", "the missing 2nd breaker is AND-neutral")
    eq(s["SPEED_STATE_REC.SORTER_{index}_ENCODER_HEALTHY"], "SORTER_01_ENCODER_HEALTHY", "sorter-only")
    g = next(r for r in t.rows if r["instanceOf-F_ESTOP1"] == "ESTOP_AREA 2")
    eq((g["TemplateType"], g["ITERATOR_STRINGS"]), ("06", []), "generic: TT06, no door slots")
    eq(g["SPEED_STATE_REC.SORTER_{index}_ENCODER_HEALTHY"], "", "no encoder on a generic area")


def test_of_variant_picks_smallest_cover():
    eq(builders._of_variant(1, 1, 1)[3], 1, "exact 1/1/1 -> TT01")
    eq(builders._of_variant(1, 3, 1)[3], 3, "fb=3 needs the cap-4 variant -> TT03")
    eq(builders._of_variant(2, 1, 1)[3], 7, "oncond=2 -> TT07")
    eq(builders._of_variant(9, 9, 9), None, "nothing covers it")


def test_builder_05_output_feedback_source_row_orders_unit():
    rows = [
        {"script_type": "KQ", "index": "7", "source_row": "20", "name_in_db": "KQ_late",
         "name_in_tagtable": "TAGQ2", "iol_FLD": "LATE", "device": "D2", "combined_FLD": "FLDx",
         "numerazione_linea": "L1", "matrix_areas": ["AREA 1"]},
        {"script_type": "KQ", "index": "7", "source_row": "5", "name_in_db": "KQ_early",
         "name_in_tagtable": "TAGQ1", "iol_FLD": "EARLY", "device": "D1", "combined_FLD": "FLDx",
         "numerazione_linea": "L1", "matrix_areas": ["AREA 1"]},
        {"script_type": "KI", "index": "7", "source_row": "8", "name_in_tagtable": "TAGI1"},
    ]
    t = builders.build_05_output_feedback(Database(rows))
    eq(len(t), 1, "one contactor unit (index 7)")
    r = t.rows[0]
    eq(r["03_FDBACK_RAW.{db_element}"], "KQ_early", "source_row sort -> the earliest KQ is kq0")
    eq(r["instanceOf-F_FDBACK"], "FDBACK_EARLY_D2", "instanceOf = kq0 FLD + each extra KQ's device")
    eq(r["tagName:Contactor1_Output"], "TAGQ1")
    eq(r["tagName:Contactor1_QBadInput"], "QBAD_TAGQ1")
    eq(r["NetworkComment"], "AREA 1 Contactor Output FLDx L1", "matrix_areas |-joined, whitespace collapsed")
    eq(r["05_EM_STATE.{matrix_areas.1}"], "AREA 1 Q_Delayed")


def test_builder_05_output_feedback_pads_feedback_slots():
    rows = [
        {"script_type": "KQ", "index": "9", "source_row": "1", "name_in_db": "KQ9",
         "name_in_tagtable": "TQ", "iol_FLD": "F", "matrix_areas": ["AREA 1"]},
        {"script_type": "KI", "index": "9", "source_row": "2", "name_in_tagtable": "TI"},
    ]
    t = builders.build_05_output_feedback(Database(rows))
    r = t.rows[0]
    eq(r["TemplateType"], "01", "1 oncond / 1 fb / 1 co -> TT01")
    eq(r["tagName:Contactor1_FeedbackInput"], "TI", "the one real KI")


def test_builder_08_gate_manager_sorters_and_doors():
    node = _node("n1", "1.2.3.4", i0="0", i1="20", q0="0", q1="20")
    rows = [
        node,
        {"script_type": "N1/2", "index": "1"},                         # a sorter -> one TT01 row
        {"script_type": "DI1/2", "index": "5", "bit": "I1.0", "name_in_db": "D_in", "iol_FLD": "DOORA",
         "name_in_tagtable": "TDI1", "IsSorterArea": "yes"},
        {"script_type": "DR", "index": "5", "name_in_tagtable": "TDR"},  # reset exists
        {"script_type": "DQ", "index": "5", "name_in_tagtable": "TDQ"},  # the door DQ -> one TT02 row
    ]
    t = builders.build_08_gate_manager(Database(rows))
    tt01 = [r for r in t.rows if r["TemplateType"] == "01"]
    tt02 = [r for r in t.rows if r["TemplateType"] == "02"]
    eq((len(tt01), len(tt02)), (1, 1), "one sorter row + one door row")
    eq(tt01[0]["SPEED_STATE_REC.SORTER_{index}_STOPPED"], "SORTER_01_STOPPED")
    d = tt02[0]
    eq(d["instanceOf-02_Safety_Door"], "SFDOOR_DOORA", "instanceOf from the DI anchor FLD")
    eq(d["00_Commissioning.{db_element}"], "n1 1.2.3.4", "bypass = the DI's node")
    eq(d["tagName:DoorClosedCh1"], "TDI1")
    eq(d["tagName:DoorSolenoidUnlock"], "TDQ")
    eq((d["choice:IsSorterDoor"], d["choice:DoorResetNecessary"]), ("Always TRUE", "Always TRUE"))


# --- build -> project round-trip (the SSOT tables -> CSV) -------------------------------------- #
def test_project_reconstructs_from_tables():
    blk, mem = engine.software_blocks_table(), engine.software_block_members_table()
    blk.add(name="00_X", template_stem="TEMPLATE--v1.0--00_X", template_ref="C:/tpl/00_X.xml",
            keys=["TemplateType", "NetworkComment"], columns=["TemplateType", "NetworkComment", "ITER"])
    mem.add(block="00_X", seq=0, values={"TemplateType": "01", "NetworkComment": "n1", "ITER": ["a", "b"]})
    mem.add(block="00_X", seq=1, values={"TemplateType": "01", "NetworkComment": "n2", "ITER": ["c"]})
    with tempfile.TemporaryDirectory() as d:
        res = engine.project(DB([blk, mem]), out_dir=d)
        eq((res["count"], res["findings"]), (1, []), "one CSV, pure projection")
        lines = open(res["files"][0], encoding="utf-8").read().splitlines()
        eq(lines[2], "%,TemplateType,!!NetworkComment$$,!!ITER$$")
        eq(lines[3], "@,01,n1,a,b")
        eq(lines[4], "@,01,n2,c", "rows projected in seq order, the ITERATOR spread preserved")


# --- 800c: the 03 FC-XML emit (xml_emit) ------------------------------------------------------- #
_FC_TEMPLATE = (
    '<?xml version="1.0" encoding="utf-8"?>\r\n'
    '<Document>\r\n'
    '  <Engineering version="V18" />\r\n'
    '  <SW.Blocks.FC ID="0">\r\n'
    '    <AttributeList>\r\n'
    '      <Name>TEMPLATE--v1.0--03_Zone Cumulative</Name>\r\n'
    '      <Number>19</Number>\r\n'
    '      <ProgrammingLanguage>F_FBD</ProgrammingLanguage>\r\n'
    '    </AttributeList>\r\n'
    '    <ObjectList>\r\n'
    '    </ObjectList>\r\n'
    '  </SW.Blocks.FC>\r\n'
    '</Document>'
)


def _write_fc_template(d):
    path = os.path.join(d, "TEMPLATE--v1.0--03_Zone Cumulative.xml")
    with open(path, "w", encoding="utf-8-sig", newline="") as f:   # real templates carry a BOM
        f.write(_FC_TEMPLATE)
    return path


def test_and_coil_fc_one_network_per_row():
    with tempfile.TemporaryDirectory() as d:
        tpl = _write_fc_template(d)
        t = Table("03_Zone Cumulative")
        t.add(template_type="01", nameOfDB="01_Pushbutton", NetworkComment="AREA 1 PB - Infeed",
              **{"02_COM.{db_element}": "AREA 1 PB"}, ITERATOR_STRINGS=["PB_A", "PB_B"])
        t.add(template_type="01", nameOfDB="03_FDBACK", NetworkComment="AREA 1 FDB",
              **{"02_COM.{db_element}": "AREA 1 FDB"}, ITERATOR_STRINGS=[])   # no inputs -> skipped
        xml = xml_emit.and_coil_fc(t, tpl, "03_Zone Cumulative")
        ok("<Name>03_Zone Cumulative</Name>" in xml, "the <Name> is swapped to the block name")
        eq(xml.count("<SW.Blocks.CompileUnit"), 1, "one network per @ row WITH inputs (empty row skipped)")
        ok('<TemplateValue Name="Card" Type="Cardinality">2</TemplateValue>' in xml, "A Card = the input count")
        ok('<Component Name="01_Pushbutton" />' in xml and '<Component Name="PB_A" />' in xml, "input = nameOfDB.member")
        ok('<Component Name="02_COM" />' in xml and '<Component Name="AREA 1 PB" />' in xml, "coil = 02_COM.<element>")
        ok("\r\n" in xml and not xml.startswith("﻿"), "CRLF, no BOM in the body (BOM added on write)")


def test_write_fc_xml_bom_and_path():
    with tempfile.TemporaryDirectory() as d:
        tpl = _write_fc_template(d)
        out = os.path.join(d, "import")
        t = Table("03_Zone Cumulative")
        t.add(template_type="01", nameOfDB="01_Pushbutton", NetworkComment="c",
              **{"02_COM.{db_element}": "AREA 1 PB"}, ITERATOR_STRINGS=["PB_A"])
        path = xml_emit.write_fc_xml("03_Zone Cumulative", t, tpl, out)
        eq(os.path.basename(path), "03_Zone Cumulative.xml")
        raw = open(path, "rb").read()
        ok(raw.startswith(b"\xef\xbb\xbf"), "the file carries a single UTF-8 BOM")
        ok(b"\r\n" in raw, "CRLF line endings")
        eq(xml_emit.write_fc_xml("00_Only for Commissioning", t, tpl, out), "", "a non-emitter block -> '' (no XML)")


def test_project_03_emits_xml_and_drops_csv():
    with tempfile.TemporaryDirectory() as d:
        tpl = _write_fc_template(d)
        creation, imp = os.path.join(d, "creation"), os.path.join(d, "import")
        os.makedirs(creation)
        stale = os.path.join(creation, "03_Zone Cumulative.csv")
        open(stale, "w").write("stale")                              # a stale CSV from a pre-800c run
        blk, mem = engine.software_blocks_table(), engine.software_block_members_table()
        blk.add(name="03_Zone Cumulative", template_stem="TEMPLATE--v1.0--03_Zone Cumulative", template_ref=tpl,
                keys=["TemplateType"], columns=["TemplateType", "nameOfDB", "02_COM.{db_element}", "NetworkComment", "ITERATOR_STRINGS"])
        blk.add(name="00_X", template_stem="TEMPLATE--v1.0--00_X", template_ref="C:/tpl/00_X.xml",
                keys=["TemplateType", "NetworkComment"], columns=["TemplateType", "NetworkComment"])
        mem.add(block="03_Zone Cumulative", seq=0,
                values={"TemplateType": "01", "nameOfDB": "01_Pushbutton", "02_COM.{db_element}": "AREA 1 PB",
                        "NetworkComment": "c", "ITERATOR_STRINGS": ["PB_A", "PB_B"]})
        mem.add(block="00_X", seq=0, values={"TemplateType": "01", "NetworkComment": "n1"})
        res = engine.project(DB([blk, mem]), out_dir=creation, import_dir=imp)
        eq((res["count"], len(res["xml_files"])), (1, 1), "00_X -> CSV, 03 -> XML (count = CSVs only)")
        ok(not os.path.exists(stale), "the stale 03 CSV is removed")
        ok(os.path.exists(os.path.join(imp, "03_Zone Cumulative.xml")), "03 FC XML written to import dir")
        ok(os.path.exists(os.path.join(creation, "00_X.csv")), "00_X CSV still written")


# (the transitional 800c builder-column DB writer was retired: 02_COM/05_EM_STATE are ordinary 520
#  config DBs now - per-area element rows in datablock_elements.csv; see test_datablocks/test_dbtemplate)


def test_project_ships_templates_with_relative_refs():
    # the CreationInfo folder is SELF-CONTAINED (user spec): the template XML copies to
    # Templates/ and the CSV references it relatively - an absolute PL path is dead on the OP machine
    with tempfile.TemporaryDirectory() as d:
        src = os.path.join(d, "TEMPLATE--v1.0--00_X.xml")
        with open(src, "w", encoding="utf-8-sig", newline="") as f:    # real templates carry a BOM
            f.write("<Document>tpl</Document>\r\n")
        creation = os.path.join(d, "creation")
        blk, mem = engine.software_blocks_table(), engine.software_block_members_table()
        blk.add(name="00_X", template_stem="TEMPLATE--v1.0--00_X", template_ref=src,
                keys=["TemplateType"], columns=["TemplateType"])
        mem.add(block="00_X", seq=0, values={"TemplateType": "01"})
        res = engine.project(DB([blk, mem]), out_dir=creation)
        lines = open(res["files"][0], encoding="utf-8").read().splitlines()
        eq(lines[0], "$,template=Templates/TEMPLATE--v1.0--00_X.xml",
           "the CSV references the SHIPPED template, relative to its own folder")
        shipped = os.path.join(creation, "Templates", "TEMPLATE--v1.0--00_X.xml")
        ok(os.path.exists(shipped), "the template ships WITH the CreationInfo CSVs")
        eq(open(shipped, "rb").read(), open(src, "rb").read(), "a byte-exact copy (BOM preserved)")
        # a block with NO shippable template: the relative ref still writes, nothing is copied
        blk2, mem2 = engine.software_blocks_table(), engine.software_block_members_table()
        blk2.add(name="99_Y", template_stem="99_Y", template_ref=os.path.join(d, "nope", "99_Y.xml"),
                 keys=["TemplateType"], columns=["TemplateType"])
        mem2.add(block="99_Y", seq=0, values={"TemplateType": "01"})
        creation2 = os.path.join(d, "creation2")
        res2 = engine.project(DB([blk2, mem2]), out_dir=creation2)
        eq(open(res2["files"][0], encoding="utf-8").read().splitlines()[0],
           "$,template=Templates/99_Y.xml", "the ref stays relative even when the source is absent")
        ok(not os.path.exists(os.path.join(creation2, "Templates")),
           "a missing source ships nothing (the OP import reports it, like the old dangling path)")


# --- the verbose 800 log data ------------------------------------------------------------------- #
def test_block_report_verbose_log_data():
    blk, mem = engine.software_blocks_table(), engine.software_block_members_table()
    blk.add(name="05_Output Feedback", template_stem="TEMPLATE--v1.0--05_Output Feedback",
            template_ref="r", keys=["TemplateType"], columns=["TemplateType", "instanceOf-FDBACK"])
    blk.add(name="03_Zone Cumulative", template_stem="TEMPLATE--v1.0--03_Zone Cumulative",
            template_ref="r", keys=["TemplateType"], columns=["TemplateType"])
    blk.add(name="99_Unknown", template_stem="99_Unknown", template_ref="r",     # stem == name: no template
            keys=["TemplateType"], columns=["TemplateType"])
    mem.add(block="05_Output Feedback", seq=0, values={"instanceOf-FDBACK": "FDBACK_A"})
    mem.add(block="05_Output Feedback", seq=1, values={"instanceOf-FDBACK": ""})   # blank -> no instance
    rep = engine.block_report(DB([blk, mem]))
    eq([r["name"] for r in rep], ["05_Output Feedback", "03_Zone Cumulative", "99_Unknown"],
       "one report entry per built block, in table order")
    r5 = rep[0]
    eq(r5["template_stem"], "TEMPLATE--v1.0--05_Output Feedback")
    eq(r5["builder"], "builders.build_05_output_feedback", "the registered builder function resolves")
    eq((r5["emit"], r5["rows"], r5["instances"]), ("csv", 2, 1),
       "declared surface + @-row count + only the NON-EMPTY instanceOf cells count")
    eq(rep[1]["emit"], "fc_xml", "03 declares the FC-XML surface at registration")
    eq((rep[2]["template_stem"], rep[2]["builder"]), ("", "-"),
       "no shipped template -> '' (the log omits it); an unregistered block -> '-'")


# --- 800c: InstanceDBs.csv --------------------------------------------------------------------- #
def test_write_instance_dbs_merge_and_dedup():
    with tempfile.TemporaryDirectory() as d:
        blk, mem, idb = engine.software_blocks_table(), engine.software_block_members_table(), instance_dbs_table()
        blk.add(name="05_Output Feedback", template_stem="s", template_ref="r",
                keys=["TemplateType"], columns=["TemplateType", "instanceOf-FDBACK"])
        blk.add(name="07_Speed Control", template_stem="s", template_ref="r",
                keys=["TemplateType"], columns=["TemplateType", "instanceOf-01_Speed_Control_SLS"])
        mem.add(block="05_Output Feedback", seq=0, values={"instanceOf-FDBACK": "FDBACK_A"})
        mem.add(block="05_Output Feedback", seq=1, values={"instanceOf-FDBACK": "FDBACK_B"})
        mem.add(block="07_Speed Control", seq=0, values={"instanceOf-01_Speed_Control_SLS": "SLS_SORTER_01"})
        idb.add(instance_name="DiagTags_1", fb="BoolToUDInt")            # a 520 config family
        idb.add(instance_name="FDBACK_A", fb="FDBACK")                   # collides with a builder cell -> dropped
        res = engine.write_instance_dbs(DB([blk, mem, idb]), out_dir=d)
        eq(res["count"], 4, "FDBACK_A, FDBACK_B, SLS_SORTER_01, DiagTags_1 (the config dup dropped)")
        lines = open(res["path"], encoding="utf-8").read().splitlines()
        eq(lines[0], "#,Instance DBs created directly via CreateInstanceDB")
        eq(lines[1], "%,Name,InstanceOf,Number,Folder")
        eq(lines[2], "@,FDBACK_A,FDBACK,,FDBACK", "builder cells first, in block/column/seq order")
        eq(lines[3], "@,FDBACK_B,FDBACK,,FDBACK")
        eq(lines[4], "@,SLS_SORTER_01,01_Speed_Control_SLS,,01_Speed_Control_SLS")
        eq(lines[5], "@,DiagTags_1,BoolToUDInt,,BoolToUDInt", "then the 520 config families (dup name dropped)")
        raw = open(res["path"], "rb").read()
        ok(not raw.startswith(b"\xef\xbb\xbf"), "InstanceDBs.csv is plain UTF-8 (no BOM)")


if __name__ == "__main__":
    import sys
    sys.exit(run("blocks", [
        ("table_add_tracks_columns_and_iterator", test_table_add_tracks_columns_and_iterator),
        ("database_list_cell_filters", test_database_list_cell_filters),
        ("serialization_wrap_order_and_iterator", test_serialization_wrap_order_and_iterator),
        ("write_creation_csv_layout", test_write_creation_csv_layout),
        ("builder_00_commissioning", test_builder_00_commissioning),
        ("builder_06_feedback_error_chunks_to_8", test_builder_06_feedback_error_chunks_to_8),
        ("builder_07_speed_control_pairs_encoders", test_builder_07_speed_control_pairs_encoders),
        ("builder_02_em_push_button_groups_inputs", test_builder_02_em_push_button_groups_inputs),
        ("area_descriptions_reads_list_cells", test_area_descriptions_reads_list_cells),
        ("builder_03_zone_cumulative_per_area_group", test_builder_03_zone_cumulative_per_area_group),
        ("builder_04_estop_sorter_tier_and_generic", test_builder_04_estop_sorter_tier_and_generic),
        ("of_variant_picks_smallest_cover", test_of_variant_picks_smallest_cover),
        ("builder_05_output_feedback_source_row_orders_unit", test_builder_05_output_feedback_source_row_orders_unit),
        ("builder_05_output_feedback_pads_feedback_slots", test_builder_05_output_feedback_pads_feedback_slots),
        ("builder_08_gate_manager_sorters_and_doors", test_builder_08_gate_manager_sorters_and_doors),
        ("project_reconstructs_from_tables", test_project_reconstructs_from_tables),
        ("and_coil_fc_one_network_per_row", test_and_coil_fc_one_network_per_row),
        ("write_fc_xml_bom_and_path", test_write_fc_xml_bom_and_path),
        ("project_03_emits_xml_and_drops_csv", test_project_03_emits_xml_and_drops_csv),
        ("project_ships_templates_with_relative_refs", test_project_ships_templates_with_relative_refs),
        ("block_report_verbose_log_data", test_block_report_verbose_log_data),
        ("write_instance_dbs_merge_and_dedup", test_write_instance_dbs_merge_and_dedup),
    ]))
