"""The phase-800 engine: run each registered builder over the Database, serialize each Table into
the kept `$/#/%/@` CreationInfo CSV, and collect InstanceDBs.csv. No rules, no sidecars, no
block_templates.json (deprecated).

The 810 shell (SoftwareBlocks.xlsx) is the KEY INVENTORY: its sheet's `%` row is the FULL key set
and its B2 is the `$ <mode>`:
  - fill / keep -> run the builder(db) -> Table; the % header is the shell's full key set (builder
    values fill it, blanks for the rest).
  - override    -> the hand-authored @ rows IN the shell sheet ARE the table (builder skipped).
The `$ template=` reference is the ABSOLUTE path to the template .xml (apps ship as one package).
Output names drop the `TEMPLATE--vX.Y--` prefix. No golden yet - produced fresh for review.
"""
from __future__ import annotations
import csv
import os

from pipeline3.core import config
from pipeline3.domain import datablocks, signals
from pipeline3.domain.blocks.database import Database
from pipeline3.domain.blocks.table import Table
from pipeline3.domain.blocks.registry import registry
from pipeline3.domain.blocks import shells, xml_emit

INSTANCE_OF = "instanceOf-"
COM_MEMBER_COL = "02_COM.{db_element}"   # builders writing this column define the 02_COM custom DB members


def _wrap(col: str) -> str:
    """% / @ header form: TemplateType + #meta columns unwrapped; placeholders are !!key$$."""
    return col if (col == "TemplateType" or col.startswith("#")) else f"!!{col}$$"


def _ordered_columns(canonical_keys, table) -> list:
    """The shell's full key set first (TemplateType leading), then any extra builder columns; list
    (ITERATOR) columns moved last."""
    cols = list(canonical_keys)
    for c in table.columns:
        if c not in cols:
            cols.append(c)

    def is_iter(c):
        return any(isinstance(r.get(c), (list, tuple)) for r in table.rows)
    iters = [c for c in cols if c != "TemplateType" and is_iter(c)]
    scal = [c for c in cols if c != "TemplateType" and c not in iters]
    head = ["TemplateType"] if "TemplateType" in cols else []
    return head + scal + iters


def _at_row_cells(row, ordered) -> list:
    """The @-row cells for `ordered` columns: scalars as-is, a list value spread across cells (the
    horizontal ITERATOR). Shared by the CSV writer and the shell-sheet mirror so they match exactly."""
    cells = []
    for c in ordered:
        v = row.get(c, "")
        if isinstance(v, (list, tuple)):
            cells.extend("" if x is None else str(x) for x in v)
        else:
            cells.append("" if v is None else str(v))
    return cells


def _write_csv_rows(creation_dir: str, name: str, template_ref: str, header_cells, at_rows) -> str:
    """Write the $/#/%/@ CreationInfo CSV from already-serialized % header + @ rows (the builder's, or
    a shell sheet's verbatim cells in override mode)."""
    path = os.path.join(creation_dir, f"{name}.csv")
    os.makedirs(creation_dir, exist_ok=True)
    with open(path, "w", newline="", encoding="utf-8") as f:
        w = csv.writer(f)
        w.writerow(["$", f"template={template_ref}"])
        w.writerow(["#", "generated by pipeline3 (phase 800)"])
        w.writerow(["%"] + list(header_cells))
        for r in at_rows:
            w.writerow(["@"] + list(r))
    return path


def write_creation_csv(creation_dir: str, table, template_ref: str, canonical_keys) -> str:
    """Serialize one Table to CreationInfo/<name>.csv in the $/#/%/@ layout, with the % header = the
    shell's full key set (canonical_keys) + any extra builder columns."""
    ordered = _ordered_columns(canonical_keys, table)
    return _write_csv_rows(creation_dir, table.name, template_ref,
                           [_wrap(c) for c in ordered], [_at_row_cells(r, ordered) for r in table.rows])
    return path


def _com_members(tables) -> list:
    """Distinct 02_COM.{db_element} cumulatives across all built tables, in first-seen order (the
    zone-cumulative custom DB members - phase 800 owns the 02_COM DB)."""
    out = []
    for t in tables:
        if COM_MEMBER_COL not in t.columns:
            continue
        for r in t.rows:
            v = str(r.get(COM_MEMBER_COL, "") or "").strip()
            if v and v not in out:
                out.append(v)
    return out


def write_com_db(out_root, tables, emit=print) -> str:
    """The block builder's task: emit the 02_COM custom DB (safe F_DB XML) - the standard DB seed
    members (Always FALSE/TRUE/No Operation) followed by the builders' 02_COM.{db_element} cumulatives.
    signals.write_safe_db is just the DB-format primitive; the membership is decided here in phase 800."""
    cumulatives = _com_members(tables)
    if not cumulatives:
        return ""
    members = list(signals.DB_CONSTANTS) + cumulatives
    path = signals.write_safe_db(out_root, signals.COM_DB, members)
    if path:
        emit(f"zone-cumulative DB: {signals.COM_DB} ({len(members)} member(s)) -> {path}")
    return path


def _instance_rows(tables) -> list:
    """(name, fb) for every non-empty instanceOf-<FB> cell across all tables (-> InstanceDBs.csv)."""
    out = []
    for t in tables:
        for c in [c for c in t.columns if c.startswith(INSTANCE_OF)]:
            fb = c[len(INSTANCE_OF):]
            for r in t.rows:
                name = str(r.get(c, "") or "").strip()
                if name:
                    out.append((name, fb))
    return out


def _config_instance_rows(rows) -> list:
    """(name, fb) for the Instance-DB families declared in datablock_definitions.csv (the per-cabinet
    DiagnosticTags FB instances etc.). Uses the SAME datablocks.generate as phase 520, so the names match
    the DiagnosticTags members + the 620 SCL references. (A config error already halted phase 520.)"""
    if not rows:
        return []
    _g, inst, errors, _w = datablocks.generate(
        rows, config.load_db_definitions(), config.load_db_elements(), config.load_db_types())
    return [] if errors else inst


def write_instance_dbs(creation_dir: str, tables, rows=None) -> tuple:
    pairs, seen, deduped = _instance_rows(tables) + _config_instance_rows(rows), set(), []
    for name, fb in pairs:                                       # the builder cells + the config families
        if name and name not in seen:
            seen.add(name)
            deduped.append((name, fb))
    path = os.path.join(creation_dir, "InstanceDBs.csv")
    with open(path, "w", newline="", encoding="utf-8") as f:
        w = csv.writer(f)
        w.writerow(["#", "Instance DBs created directly via CreateInstanceDB"])
        w.writerow(["%", "Name", "InstanceOf", "Number", "Folder"])
        for name, fb in deduped:
            w.writerow(["@", name, fb, "", fb])
    return path, len(deduped)


def generate_blocks(rows, out_root: str, emit=print, write_instances: bool = True) -> dict:
    """820 (+830): run the registered builders (honoring 810 shell modes + key inventory), write the
    CreationInfo CSVs, and (when write_instances) InstanceDBs.csv. Returns a result dict."""
    db = Database(rows)
    creation_dir = config.out_path(out_root, "blocks_creation_dir")
    os.makedirs(creation_dir, exist_ok=True)
    info = shells.read_shells(out_root)             # {name: {mode, stem, ref, keys}}
    fallback = {shells._short(stem): stem for stem in shells.scan_templates()}   # short -> stem (no shell yet)
    builders = registry()
    names = list(builders) + [n for n, i in info.items() if i["mode"] == "override" and n not in builders]

    import_dir = config.out_path(out_root, "blocks_import_dir")
    tmpl_keys = shells.scan_templates()             # {stem: [keys]} - coil sheets aren't the key inventory
    tables, files, xml_files, warnings = [], [], [], []
    for name in names:
        si = info.get(name)
        ref = si["ref"] if si else shells.template_ref(fallback.get(name, name))
        stem = si["stem"] if si else fallback.get(name, name)
        mode = si["mode"] if si else "fill"
        is_coil = name in shells.COIL_COLUMN_BLOCKS
        keys = (["TemplateType"] + tmpl_keys.get(stem, [])) if is_coil else (si["keys"] if si else [])
        if mode == "override":
            table = (shells.read_coil_columns(out_root, name) if is_coil
                     else shells.read_override_table(out_root, name))
            if table is None:
                warnings.append(f"{name}: override mode but no shell rows - skipped")
                continue
        else:
            fn = builders.get(name)
            if fn is None:
                continue
            table = fn(db) or Table(name)
            if len(table) == 0:
                warnings.append(f"{name}: builder returned no rows (stub?) - header only")
            if is_coil and mode == "fill":                          # seed/refresh the editable coil sheet
                shells.write_coil_columns(out_root, name, table, ref)
        tables.append(table)
        # task 2: a block with a direct-XML emitter ships as a ready FC XML in ImportReady; Open2App
        # imports the XML, not the CSV, so the CreationInfo CSV is dropped (and any stale one removed).
        xml_path = xml_emit.write_fc_xml(name, table, ref, import_dir)
        if xml_path:
            xml_files.append(xml_path)
            stale_csv = os.path.join(creation_dir, f"{table.name}.csv")
            if os.path.exists(stale_csv):
                os.remove(stale_csv)
            emit(f"  FC XML: {name} ({len(table)} network(s)) -> {xml_path}")
        elif mode == "override":
            # override = write the CSV from the shell sheet AS-IS (verbatim, preserving any ITERATOR
            # spread); the table above is only for InstanceDBs (instanceOf is scalar).
            header_cells, at_rows = shells.read_override_grid(out_root, name)
            files.append(_write_csv_rows(creation_dir, name, ref, header_cells, at_rows))
        else:
            files.append(write_creation_csv(creation_dir, table, ref, keys))
            if mode == "fill":                            # seed the standard shell sheet = a copy of the CSV
                ordered = _ordered_columns(keys, table)
                shells.write_standard_sheet(out_root, name, [_wrap(c) for c in ordered],
                                            [_at_row_cells(r, ordered) for r in table.rows], ref)

    com_path = write_com_db(out_root, tables, emit)   # the 02_COM zone-cumulative custom DB (phase 800)

    inst_n, inst_path = 0, ""
    if write_instances:
        inst_path, inst_n = write_instance_dbs(creation_dir, tables, rows)
    for w in warnings:
        emit(f"  WARN {w}")
    emit(f"software blocks: {len(files)} CSV(s)"
         + (f" + {len(xml_files)} FC XML" if xml_files else "")
         + (f" + {inst_n} instance(s)" if write_instances else "") + f" -> {creation_dir}")
    return {"dir": creation_dir, "files": files, "xml_files": xml_files, "instances": inst_n,
            "instance_path": inst_path, "com_path": com_path, "warnings": warnings, "count": len(files)}
