"""The phase-800 engine: run each registered builder over the Database, serialize each Table into
the kept `$/#/%/@` CreationInfo CSV, and collect InstanceDBs.csv. No rules, no sidecars, no
block_templates.json (deprecated).

The 810 shell (SoftwareBlocks.xlsx) is the KEY INVENTORY: its sheet's `%` row is the FULL key set
and its B2 is the `$ <mode>`:
  - fill / keep -> run the builder(db) -> Table; the % header is the shell's full key set (builder
    values fill it, blanks for the rest).
  - override    -> the hand-authored @ rows IN the shell sheet ARE the table (builder skipped).
The `$ template=` reference is the ABSOLUTE path to the template .xml (apps ship as one package).
Output names drop the `TEMPLATE--vX.Y--` prefix. No golden yet - produced fresh for review.
"""
from __future__ import annotations
import csv
import os

from pipeline3.core import config
from pipeline3.domain.blocks.database import Database
from pipeline3.domain.blocks.table import Table
from pipeline3.domain.blocks.registry import registry
from pipeline3.domain.blocks import shells

INSTANCE_OF = "instanceOf-"


def _wrap(col: str) -> str:
    """% / @ header form: TemplateType + #meta columns unwrapped; placeholders are !!key$$."""
    return col if (col == "TemplateType" or col.startswith("#")) else f"!!{col}$$"


def _ordered_columns(canonical_keys, table) -> list:
    """The shell's full key set first (TemplateType leading), then any extra builder columns; list
    (ITERATOR) columns moved last."""
    cols = list(canonical_keys)
    for c in table.columns:
        if c not in cols:
            cols.append(c)

    def is_iter(c):
        return any(isinstance(r.get(c), (list, tuple)) for r in table.rows)
    iters = [c for c in cols if c != "TemplateType" and is_iter(c)]
    scal = [c for c in cols if c != "TemplateType" and c not in iters]
    head = ["TemplateType"] if "TemplateType" in cols else []
    return head + scal + iters


def write_creation_csv(creation_dir: str, table, template_ref: str, canonical_keys) -> str:
    """Serialize one Table to CreationInfo/<name>.csv in the $/#/%/@ layout, with the % header = the
    shell's full key set (canonical_keys) + any extra builder columns."""
    ordered = _ordered_columns(canonical_keys, table)
    path = os.path.join(creation_dir, f"{table.name}.csv")
    os.makedirs(creation_dir, exist_ok=True)
    with open(path, "w", newline="", encoding="utf-8") as f:
        w = csv.writer(f)
        w.writerow(["$", f"template={template_ref}"])
        w.writerow(["#", "generated by pipeline3 (phase 800)"])
        w.writerow(["%"] + [_wrap(c) for c in ordered])
        for r in table.rows:
            cells = []
            for c in ordered:
                v = r.get(c, "")
                if isinstance(v, (list, tuple)):
                    cells.extend("" if x is None else str(x) for x in v)   # horizontal ITERATOR
                else:
                    cells.append("" if v is None else str(v))
            w.writerow(["@"] + cells)
    return path


def _instance_rows(tables) -> list:
    """(name, fb) for every non-empty instanceOf-<FB> cell across all tables (-> InstanceDBs.csv)."""
    out = []
    for t in tables:
        for c in [c for c in t.columns if c.startswith(INSTANCE_OF)]:
            fb = c[len(INSTANCE_OF):]
            for r in t.rows:
                name = str(r.get(c, "") or "").strip()
                if name:
                    out.append((name, fb))
    return out


def write_instance_dbs(creation_dir: str, tables) -> tuple:
    rows = _instance_rows(tables)
    path = os.path.join(creation_dir, "InstanceDBs.csv")
    with open(path, "w", newline="", encoding="utf-8") as f:
        w = csv.writer(f)
        w.writerow(["#", "Instance DBs created directly via CreateInstanceDB"])
        w.writerow(["%", "Name", "InstanceOf", "Number", "Folder"])
        for name, fb in rows:
            w.writerow(["@", name, fb, "", fb])
    return path, len(rows)


def generate_blocks(rows, out_root: str, emit=print, write_instances: bool = True) -> dict:
    """820 (+830): run the registered builders (honoring 810 shell modes + key inventory), write the
    CreationInfo CSVs, and (when write_instances) InstanceDBs.csv. Returns a result dict."""
    db = Database(rows)
    creation_dir = config.out_path(out_root, "blocks_creation_dir")
    os.makedirs(creation_dir, exist_ok=True)
    info = shells.read_shells(out_root)             # {name: {mode, stem, ref, keys}}
    fallback = {shells._short(stem): stem for stem in shells.scan_templates()}   # short -> stem (no shell yet)
    builders = registry()
    names = list(builders) + [n for n, i in info.items() if i["mode"] == "override" and n not in builders]

    tables, files, warnings = [], [], []
    for name in names:
        si = info.get(name)
        keys = si["keys"] if si else []
        ref = si["ref"] if si else shells.template_ref(fallback.get(name, name))
        mode = si["mode"] if si else "fill"
        if mode == "override":
            table = shells.read_override_table(out_root, name)
            if table is None:
                warnings.append(f"{name}: override mode but no shell rows - skipped")
                continue
        else:
            fn = builders.get(name)
            if fn is None:
                continue
            table = fn(db) or Table(name)
            if len(table) == 0:
                warnings.append(f"{name}: builder returned no rows (stub?) - header only")
        files.append(write_creation_csv(creation_dir, table, ref, keys))
        tables.append(table)

    inst_n, inst_path = 0, ""
    if write_instances:
        inst_path, inst_n = write_instance_dbs(creation_dir, tables)
    for w in warnings:
        emit(f"  WARN {w}")
    emit(f"software blocks: {len(files)} CSV(s)"
         + (f" + {inst_n} instance(s)" if write_instances else "") + f" -> {creation_dir}")
    return {"dir": creation_dir, "files": files, "instances": inst_n,
            "instance_path": inst_path, "warnings": warnings, "count": len(files)}
