#!/usr/bin/env python3
"""softwareblocks.py — generate the SoftwareBlocksBuilder CSV(s) from block_builders.

Loads the CentralDatabase (staging), calls each registered builder, and writes one
CSV per template in the SoftwareBlocksBuilder format:

  $  template=...                 directive (the .xml template)
  #  comment
  %  TemplateType,#Templates Capacity,#Templates Index,#Elements Needed,!!key$$...
  @  one block instance: TemplateType + #Elements Needed + the key values; the
     ITERATOR (the list-valued key) expands rightward, padded to the chosen
     capacity with the instance's pad value.

#Elements Needed = the real element count; TemplateType = the Index of the smallest
Capacity >= that count, from the template's sidecar capacity CSV (rides along in cols
C/D for reference). Not part of the pipeline.

  python softwareblocks.py [--out DIR]
"""
from __future__ import annotations
import argparse
import csv
import os
import sys

_HERE = os.path.dirname(os.path.abspath(__file__))
if _HERE not in sys.path:
    sys.path.insert(0, _HERE)

from safetydb import config, staging
import block_builders
import block_templates

TEMPLATES_DIR = os.path.join(_HERE, "Templates", "Tia Portal Software Blocks")
META_COLS = ["TemplateType", "#Templates Capacity", "#Templates Index", "#Elements Needed"]
TEMPLATE_PATH_PREFIX = r"\XML Templates"   # how the $ directive references the template


def _abs(path: str) -> str:
    return path if os.path.isabs(path) else os.path.normpath(os.path.join(_HERE, path))


def _load_capacity(stem: str) -> list:
    """Sidecar capacity CSV (same name as the template) -> sorted [(capacity, index)]."""
    path = os.path.join(TEMPLATES_DIR, stem + ".csv")
    table = []
    if os.path.exists(path):
        with open(path, newline="", encoding="utf-8-sig") as f:
            for r in csv.reader(f):
                if len(r) >= 2 and str(r[0]).strip().isdigit() and str(r[1]).strip().isdigit():
                    table.append((int(r[0]), int(r[1])))
    return sorted(table)


def _pick(table: list, n: int):
    """Smallest (capacity, index) with capacity >= n; the largest tier if none fits;
    (n, '') when there is no table (no sizing -> no padding)."""
    if not table:
        return n, ""
    for cap, idx in table:
        if cap >= n:
            return cap, idx
    return table[-1]


def build_template_csv(stem: str, builder, db: list) -> list:
    """Return the CSV grid (list of rows) for one template."""
    table = _load_capacity(stem)
    instances = builder(db)
    # column keys = the union of the builders' instance keys (first-seen order); if the
    # builder produced nothing, fall back to scanning the template (no json needed).
    keys = []
    for inst in instances:
        for k in inst:
            if k != "_pad" and k not in keys:
                keys.append(k)
    if not keys:
        keys = block_templates.scan_template_keys().get(stem, [])

    # the iterator key = the one that carries a list value
    iter_key = next((k for inst in instances for k, v in inst.items() if isinstance(v, list)), None)
    scalar_keys = [k for k in keys if k != iter_key]
    ordered_keys = scalar_keys + ([iter_key] if iter_key else [])

    data_rows = []  # (template_type, n_elements, [scalar cells], [iterator cells])
    for inst in instances:
        items = list(inst.get(iter_key, [])) if iter_key else []
        n = len(items)
        cap, idx = _pick(table, n)
        pad = inst.get("_pad", block_builders.PAD)
        padded = items + [pad] * max(0, cap - n) if isinstance(cap, int) else items
        scal = [str(inst.get(k, "")) for k in scalar_keys]
        data_rows.append((idx, n, scal, padded))

    grid = []
    grid.append(["$", f"template={TEMPLATE_PATH_PREFIX}\\{stem}.xml"])
    grid.append(["#", "generated by softwareblocks.py"])
    grid.append(["%"] + META_COLS + [f"!!{k}$$" for k in ordered_keys] + ["# ----->"])

    for i in range(max(len(data_rows), len(table))):
        cell = ["", "", "", "", ""]  # marker, TemplateType, Capacity, Index, ElementsNeeded
        tail = []
        if i < len(data_rows):
            idx, n, scal, padded = data_rows[i]
            template_type = f"{idx:02d}" if isinstance(idx, int) else str(idx)
            cell[0], cell[1], cell[4] = "@", template_type, str(n)
            tail = scal + padded
        if i < len(table):
            cell[2], cell[3] = str(table[i][0]), str(table[i][1])
        grid.append(cell + tail)

    width = max(len(r) for r in grid)
    return [r + [""] * (width - len(r)) for r in grid], len(data_rows)


def generate(out_dir: str | None = None, params_path: str | None = None) -> dict:
    params = config.load_params(params_path)
    types = config.load_signal_types()
    db, _warnings = staging.load_io_list(params, types)   # CentralDatabase (has matrix_areas + name_in_db)
    out_dir = out_dir or os.path.join(_abs(params.get("output_dir", "Output")), "SoftwareBlocks")
    os.makedirs(out_dir, exist_ok=True)

    written = {}
    for stem, builder in block_builders.BUILDERS.items():
        grid, n = build_template_csv(stem, builder, db)
        path = os.path.join(out_dir, stem + ".csv")
        with open(path, "w", newline="", encoding="utf-8-sig") as f:
            csv.writer(f, lineterminator="\n").writerows(grid)
        written[stem] = (path, n)
    return written


def main():
    ap = argparse.ArgumentParser(description="Generate SoftwareBlocksBuilder CSVs from block_builders.py")
    ap.add_argument("--out", default=None, help="output dir (default Output/SoftwareBlocks)")
    args = ap.parse_args()
    for stem, (path, n) in generate(args.out).items():
        print(f"{n:3} instance(s)  ->  {path}")


if __name__ == "__main__":
    main()
