"""The byte-parity oracle: frozen PL4 vs PL5 over the same builtin documents (P-001 acceptance).

PL4 left the working branch (the slim PL5 + OP5 line, 2026-10-08): its outputs over the builtin fixture are
FROZEN in `tests/parity/pl4_reference/` (`db/` = the SSOT tables, `out/` = the generated output tree). The
oracle runs PL5's full generation chain (the GUI handlers' order, minus the document-mutating legs: no
IF_-sheet insert, no ph200 fill) into a sandbox and compares it with the reference:
  - every SSOT table CSV               byte-for-byte
  - every generated output file        byte-for-byte, with the sanctioned normalizations:
      * the CreationInfo generator comment (`generated by pipeline4` vs `pipeline5`)
      * the repository root in an absolute path -> `<REPO>` (the reference is portable - any checkout)
      * .xlsx compared by CONTENT (cells per sheet) - zip containers are not byte-stable
      * the OP5 contract-v1 header (Shared/PL5_OP5_contract.md §3): the leading `#!openn … #!end` block in
        its csv / XML-comment / `//` wrapping, and PL4's bare `#!format=2` tag line, are stripped on both
        sides - and a PL5 BuilderData file MUST carry one (a file without it, or a workbook without its
        `.openn` sidecar, is a difference: the oracle is the producer obligation's gate too)
      * the VCI-shaped workspace (contract §4): PL5's `Devices & networks/`, `Templates/`, `<PLC>/Program
        blocks/`, `<PLC>/PLC tags/` compare against the reference's legacy folders (the §4.1 mapping);
        `.openn/workspace.openn.config` and the `.openn` sidecars are PL5-only by design
      * the tag-table XML (`<PLC>/PLC tags/<Table>.xml`, contract §9.1 decided 2026-10-09): a sanctioned NEW
        surface PL4 never had - not compared, but every file must carry the header and be a well-formed
        `SW.Tags.PlcTagTable` document (counted in the summary line)
      * the coupler transfer areas (C-031, contract §2.1): the `TransferArea-*` rows of `hardware_modules.csv`
        and `Modules.csv` are PL5-only (PL4 never emitted them) - dropped from the PL5 side only, counted in the
        verdict; a reference row of that model would still be a difference
The verdict is the EXIT CODE (0 = parity): the policy lives in the command, not in log prose.

Run:         <python> scripts/parity_vs_pl4.py
Regenerate:  <python> scripts/parity_vs_pl4.py --regenerate   (needs a Pipeline4App/ beside Pipeline5App/ -
             PL4 then runs against THIS checkout's Shared/; an intentional PL5 output change is sanctioned by
             a reviewed regeneration, never by editing the reference)
"""
from __future__ import annotations

import os
import re
import shutil
import sys
import tempfile

HERE = os.path.dirname(os.path.abspath(__file__))
PL5_ROOT = os.path.dirname(HERE)
REPO = os.path.dirname(PL5_ROOT)
PL4_ROOT = os.path.join(REPO, "Pipeline4App")
REFERENCE = os.path.join(PL5_ROOT, "tests", "parity", "pl4_reference")
sys.path.insert(0, PL5_ROOT)


def run_pl4(db_dir: str, out_dir: str) -> None:
    sys.path.insert(0, PL4_ROOT)
    from pipeline4.core import config as c4
    c4._BUILTIN_DATABASE, c4._BUILTIN_OUTPUT = db_dir, out_dir
    from pipeline4.domain import (staging, datablocks, datablock_xml, interfaces, interface_xlsx,
                                  interface_scl, io_tags, diagnosis, diaglist_csv, diagnosis_scl,
                                  hardware, hardware_csv, coverage)
    from pipeline4.domain.blocks import engine
    db, f = staging.stage()
    assert not any(x.severity == "FAIL" for x in f), f"PL4 staging FAIL: {f}"
    db, _ = datablocks.build(db)
    datablock_xml.project(db)
    db, _ = interfaces.build_interfaces(db)
    interface_xlsx.project(db)                       # documentation only; the INSERT leg is skipped
    interface_scl.project(db)
    io_tags.project(db)
    db, _ = diagnosis.build(db)
    diaglist_csv.project(db)
    diagnosis_scl.project(db)
    db, _ = hardware.build(db)
    hardware_csv.project(db)
    db, _ = engine.build(db)
    engine.project(db)
    engine.write_instance_dbs(db)
    db, _ = coverage.build(db)
    coverage.project(db)


def run_pl5(db_dir: str, out_dir: str) -> None:
    from pipeline5.config import paths as p5paths
    p5paths._BUILTIN_DATABASE, p5paths._BUILTIN_OUTPUT = db_dir, out_dir
    from pipeline5.systems.plc_based.siemens_s7.safety.system import SYSTEM
    p5paths.use_system(SYSTEM)
    from pipeline5.phases.staging import iolist as staging
    from pipeline5.phases.datablocks import generator as datablocks
    from pipeline5.systems.plc_based.siemens_s7 import globaldb_xml_emitter as datablock_xml
    from pipeline5.phases.interfaces import builder as interfaces
    from pipeline5.systems.plc_based.siemens_s7 import interface_xlsx_writer as interface_xlsx
    from pipeline5.systems.plc_based.siemens_s7 import interface_scl_emitter as interface_scl
    from pipeline5.systems.plc_based.siemens_s7 import plctags_xlsx_writer as io_tags
    from pipeline5.phases.diagnosis import builder as diagnosis
    from pipeline5.phases.diagnosis import diaglist as diaglist_csv
    from pipeline5.systems.plc_based.siemens_s7.safety import opc_diagnosis_scl as diagnosis_scl
    from pipeline5.systems.plc_based.siemens_s7 import profinet_hardware as hardware
    from pipeline5.systems.plc_based.siemens_s7 import hardware_csv_export as hardware_csv
    from pipeline5.phases.software_blocks import build_engine as engine
    from pipeline5.phases.coverage import coverage
    db, f = staging.stage(system=SYSTEM)
    assert not any(x.severity == "FAIL" for x in f), f"PL5 staging FAIL: {f}"
    db, _ = datablocks.build(db, system=SYSTEM)
    datablock_xml.project(db)
    db, _ = interfaces.build_interfaces(db)
    interface_xlsx.project(db)
    interface_scl.project(db)
    io_tags.project(db)
    db, _ = diagnosis.build(db)
    diaglist_csv.project(db)
    diagnosis_scl.project(db)
    db, _ = hardware.build(db)
    hardware_csv.project(db)
    db, _ = engine.build(db, system=SYSTEM)
    engine.project(db, system=SYSTEM)
    engine.write_instance_dbs(db, system=SYSTEM)
    db, _ = coverage.build(db, system=SYSTEM)
    coverage.project(db, system=SYSTEM)


def _tree(root: str) -> dict:
    out = {}
    for r, _d, files in os.walk(root):
        for f in files:
            p = os.path.join(r, f)
            out[os.path.relpath(p, root).replace(os.sep, "/")] = p
    return out


def _repo_forms() -> list:
    """The repository root as an absolute path may appear in an output: native, forward-slash and
    JSON-escaped spellings - longest first."""
    native = os.path.abspath(REPO)
    forms = {native, native.replace("\\", "/"), native.replace("\\", "\\\\")}
    return sorted(forms, key=len, reverse=True)


# The contract-v1 header in its three wrappings + PL4's legacy tag - the oracle's OWN reading of the spec
# (never the producer's code): the XML form keeps the declaration (group 1), the others their BOM.
_HEADER_RXS = (
    re.compile(r"^(﻿?<\?xml[^>]*\?>\r?\n?)[ \t]*<!--\s*#!openn\b.*?-->\r?\n?", re.S),
    re.compile(r"^(﻿?)#!openn[^\r\n]*\r?\n(?:[^\r\n]*\r?\n)*?#!end[^\r\n]*\r?\n?"),
    re.compile(r"^(﻿?)//[ \t]*#!openn[^\r\n]*\r?\n(?:[^\r\n]*\r?\n)*?//[ \t]*#!end[^\r\n]*\r?\n?"),
)
_LEGACY_TAG_RX = re.compile(r"^(﻿?)#!format=\d+[^\r\n]*\r?\n?")


def _strip_header(text: str) -> tuple:
    """(text without its leading header block / legacy tag, whether a contract-v1 header was there)."""
    for rx in _HEADER_RXS:
        m = rx.match(text)
        if m:
            return m.group(1) + text[m.end():], True
    m = _LEGACY_TAG_RX.match(text)
    if m:
        return m.group(1) + text[m.end():], False
    return text, False


def _norm_str(text: str) -> str:
    text, _headered = _strip_header(text)
    for form in _repo_forms():
        text = text.replace(form, "<REPO>")
    return re.sub(r"generated by pipeline\d", "generated by pipeline<N>", text)


def _norm_text(data: bytes) -> bytes:
    """The sanctioned normalizations on text bytes: the generator `#` comment line + the repository root."""
    try:
        text = data.decode("utf-8")
    except UnicodeDecodeError:
        return data
    return _norm_str(text).encode("utf-8")


def _xlsx_cells(path: str):
    import openpyxl

    def norm(v):
        # ArrayFormula objects compare by identity - reduce to their comparable content
        if v.__class__.__name__ == "ArrayFormula":
            return ("ARRAY", getattr(v, "ref", None), getattr(v, "text", None))
        return _norm_str(v) if isinstance(v, str) else v

    wb = openpyxl.load_workbook(path, data_only=False)
    return {ws.title: [[norm(c.value) for c in row] for row in ws.iter_rows()] for ws in wb.worksheets}


_WORKSPACE = "TiaPortalProjectInterface/BuilderData/"
_TRANSFER_AREA_ROW = re.compile(r"(?:^|,)TransferArea-(?:IN|OUT|IN_OUT)(?:,|$)")
_MODULE_TABLES = ("hardware_modules.csv", "Modules.csv")
SANCTIONED = {"transfer_area_rows": 0, "tag_table_xml": 0, "interface_descriptions": 0, "region_comments": 0,
              "device_types_copy": 0}
_DEVICE_TYPES_COPY = _WORKSPACE + "Devices & networks/DeviceTypesDatabase.csv"
_SHARED_DEVICE_TYPES = os.path.join(REPO, "Shared", "HardwareConfigBuilderData", "DeviceTypesDatabase.csv")
_INTERFACE_SCL = "10_Machine Interfaces.scl"
_REGION_LINE = re.compile(r"^REGION\s")
_COMMENT_LINE = re.compile(r"^\s*//")


def _drop_transfer_areas(rel: str, data: bytes) -> bytes:
    """The PL5-only coupler transfer-area rows (C-031) out of a PL5 module table - every other byte kept."""
    if os.path.basename(rel) not in _MODULE_TABLES:
        return data
    text = data.decode("utf-8")
    lines = text.splitlines(keepends=True)
    kept = [line for line in lines if not _TRANSFER_AREA_ROW.search(line.rstrip())]
    SANCTIONED["transfer_area_rows"] += len(lines) - len(kept)
    return "".join(kept).encode("utf-8")


def _drop_interface_descriptions(rel: str, data: bytes) -> bytes:
    """The PL5-only interface description (C-033) out of a PL5 file: the `interfaces` table's `description`
    column, and the `//` comment line right after each `REGION` of the interfaces SCL - every other byte kept."""
    name = os.path.basename(rel)
    if name == "interfaces.csv":
        import csv
        import io
        text = data.decode("utf-8")
        bom = "\ufeff" if text.startswith("\ufeff") else ""
        rows = list(csv.reader(io.StringIO(text[len(bom):], newline="")))
        if not rows or "description" not in rows[0]:
            return data
        at = rows[0].index("description")
        out = io.StringIO(newline="")
        writer = csv.writer(out)                           # the Table writer's dialect (CRLF, minimal quoting)
        for row in rows:
            if len(row) > at and row is not rows[0] and row[at]:
                SANCTIONED["interface_descriptions"] += 1
            writer.writerow(row[:at] + row[at + 1:])
        return (bom + out.getvalue()).encode("utf-8")
    if name == _INTERFACE_SCL:
        lines = data.decode("utf-8").splitlines(keepends=True)
        kept = []
        for line in lines:
            if kept and _REGION_LINE.match(kept[-1]) and _COMMENT_LINE.match(line):
                SANCTIONED["region_comments"] += 1
                continue
            kept.append(line)
        return "".join(kept).encode("utf-8")
    return data


def _is_tag_table_xml(rel: str) -> bool:
    """A PL5 `<PLC>/PLC tags/<Table>.xml` (contract §9.1, since 2026-10-09) - the sanctioned new surface."""
    if not rel.startswith(_WORKSPACE) or not rel.lower().endswith(".xml"):
        return False
    parts = rel[len(_WORKSPACE):].split("/")
    return len(parts) >= 3 and parts[1] == "PLC tags"


def _check_tag_table_xml(rel: str, path: str, label: str) -> list:
    """What the sanctioned surface must still satisfy: the contract-v1 header and a well-formed
    `SW.Tags.PlcTagTable` document naming its table."""
    import xml.etree.ElementTree as ET
    try:
        text = open(path, "rb").read().decode("utf-8-sig")
    except UnicodeDecodeError:
        return [f"{label}: tag-table XML is not UTF-8: {rel}"]
    _body, headered = _strip_header(text)
    problems = [] if headered else [f"{label}: no #!openn header: {rel}"]
    try:
        root = ET.fromstring(text)
    except ET.ParseError as error:
        return problems + [f"{label}: tag-table XML is not well-formed: {rel} ({error})"]
    table = root.find("SW.Tags.PlcTagTable")
    if root.tag != "Document" or table is None or not (table.findtext("AttributeList/Name") or "").strip():
        problems.append(f"{label}: not a SW.Tags.PlcTagTable document with a table name: {rel}")
    return problems


def _check_device_types_copy(path: str, label: str) -> list:
    """The shipped DeviceTypesDatabase (C-036, since 2026-10-09) - a PL5-only file: a `hw/device-types` header
    citing the shared original, and below it the original byte for byte (the oracle's run reads the shared one)."""
    text = open(path, "rb").read().decode("utf-8")
    body, headered = _strip_header(text)
    problems = [] if headered else [f"{label}: no #!openn header on the shipped DeviceTypesDatabase"]
    if "#! kind: hw/device-types" not in text or "#! source: Shared/HardwareConfigBuilderData/DeviceTypesDatabase.csv" not in text:
        problems.append(f"{label}: the shipped DeviceTypesDatabase is no hw/device-types copy citing the shared one")
    original, _h = _strip_header(open(_SHARED_DEVICE_TYPES, "rb").read().decode("utf-8"))
    if body != original:
        problems.append(f"{label}: the shipped DeviceTypesDatabase differs from the shared original below its header")
    return problems


def _legacy_rel(rel: str):
    """A PL5 output path -> the frozen reference's path: the VCI-shaped workspace (contract §4) onto the
    legacy BuilderData folders (§4.1, inverted). None = a PL5-only file by design (the workspace config,
    a header sidecar) - never compared, never a difference."""
    if not rel.startswith(_WORKSPACE):
        return rel
    parts = rel[len(_WORKSPACE):].split("/")
    head, tail = parts[0], "/".join(parts[1:])
    if head == ".openn" or rel.endswith(".openn"):
        return None
    if head == "Devices & networks":
        return _WORKSPACE + "HardwareConfiguration/" + tail
    if head == "Templates":
        return _WORKSPACE + "SoftwareBlocks/CreationInfo/Templates/" + tail
    if len(parts) >= 3 and parts[1] == "Program blocks":
        name = "/".join(parts[2:])
        sub = "CreationInfo" if name.lower().endswith(".csv") else "ImportReady"
        return _WORKSPACE + f"SoftwareBlocks/{sub}/{name}"
    if len(parts) >= 3 and parts[1] == "PLC tags":
        return _WORKSPACE + "PlcTags/" + "/".join(parts[2:])
    return rel


def compare(a_root: str, b_root: str, label: str) -> list:
    """`a_root` = the PL4 reference, `b_root` = the PL5 run (its workspace paths mapped onto the legacy
    ones; every workspace file must carry the contract-v1 header)."""
    diffs = []
    a, b = _tree(a_root), {}
    for rel, path in _tree(b_root).items():
        if _is_tag_table_xml(rel):                     # the sanctioned new surface: checked, never compared
            diffs += _check_tag_table_xml(rel, path, label)
            SANCTIONED["tag_table_xml"] += 1
            continue
        if rel == _DEVICE_TYPES_COPY:                  # the shipped database: checked against its original
            diffs += _check_device_types_copy(path, label)
            SANCTIONED["device_types_copy"] += 1
            continue
        legacy = _legacy_rel(rel)
        if legacy is None:
            continue                                   # PL5-only by design
        if legacy in b:
            diffs.append(f"{label}: two PL5 files map onto {legacy}: {rel}")
        b[legacy] = path
    for rel in sorted(set(a) | set(b)):
        if rel not in a:
            diffs.append(f"{label}: PL5-only file {rel}")
            continue
        if rel not in b:
            diffs.append(f"{label}: PL4-only file {rel}")
            continue
        in_workspace = rel.startswith(_WORKSPACE)
        if rel.lower().endswith((".xlsx", ".xlsm")):
            if _xlsx_cells(a[rel]) != _xlsx_cells(b[rel]):
                diffs.append(f"{label}: xlsx content differs: {rel}")
            if in_workspace and not os.path.isfile(b[rel] + ".openn"):
                diffs.append(f"{label}: no .openn header sidecar beside the workbook: {rel}")
            continue
        raw_b = open(b[rel], "rb").read()
        if in_workspace:
            try:
                _text, headered = _strip_header(raw_b.decode("utf-8"))
            except UnicodeDecodeError:
                headered = False
            if not headered:
                diffs.append(f"{label}: no #!openn header: {rel}")
        da = _norm_text(open(a[rel], "rb").read())
        db = _norm_text(_drop_interface_descriptions(rel, _drop_transfer_areas(rel, raw_b)))
        if da != db:
            diffs.append(f"{label}: bytes differ: {rel}")
    return diffs


def regenerate() -> int:
    """Run PL4 (Pipeline4App/ beside Pipeline5App/) into the reference - text files with the repository
    root normalized to `<REPO>` so the reference is the same in every checkout."""
    if not os.path.isdir(PL4_ROOT):
        print(f"--regenerate needs a Pipeline4App/ at {PL4_ROOT}")
        return 2
    if os.path.isdir(REFERENCE):
        shutil.rmtree(REFERENCE)
    db_dir, out_dir = os.path.join(REFERENCE, "db"), os.path.join(REFERENCE, "out")
    os.makedirs(db_dir)
    os.makedirs(out_dir)
    print("running PL4 into the reference...")
    run_pl4(db_dir, out_dir)
    for path in _tree(REFERENCE).values():
        if not path.lower().endswith((".xlsx", ".xlsm")):
            data = open(path, "rb").read()
            normed = _norm_text(data)
            if normed != data:
                open(path, "wb").write(normed)
    print(f"reference written: {len(_tree(db_dir))} SSOT files + {len(_tree(out_dir))} output files -> {REFERENCE}")
    return 0


def main() -> int:
    if "--regenerate" in sys.argv[1:]:
        return regenerate()
    if not os.path.isdir(REFERENCE):
        print(f"no PL4 reference at {REFERENCE} - run with --regenerate (needs Pipeline4App/)")
        return 2
    ref_db, ref_out = os.path.join(REFERENCE, "db"), os.path.join(REFERENCE, "out")
    with tempfile.TemporaryDirectory() as tmp:
        p5db, p5out = os.path.join(tmp, "pl5", "db"), os.path.join(tmp, "pl5", "out")
        for d in (p5db, p5out):
            os.makedirs(d)
        print("running PL5 (against the frozen PL4 reference)...")
        run_pl5(p5db, p5out)
        diffs = compare(ref_db, p5db, "SSOT") + compare(ref_out, p5out, "OUTPUT")
        print(f"\ncompared {len(_tree(ref_db))} SSOT files + {len(_tree(ref_out))} output files"
              f" (+ {SANCTIONED['tag_table_xml']} sanctioned tag-table XML: header + well-formedness checked)")
        if diffs:
            print(f"PARITY BROKEN - {len(diffs)} differences:")
            for d in diffs:
                print("  ", d)
            return 1
        print("PARITY OK - 0 diffs (PL4 -> PL5 byte-identical modulo the sanctioned normalizations; "
              f"{SANCTIONED['transfer_area_rows']} PL5-only transfer-area rows, "
              f"{SANCTIONED['interface_descriptions']} interface descriptions + "
              f"{SANCTIONED['region_comments']} SCL region comments, {SANCTIONED['device_types_copy']} shipped "
              "DeviceTypesDatabase checked against its original)")
        return 0


if __name__ == "__main__":
    sys.exit(main())
