"""The byte-parity oracle: frozen PL4 vs PL5 over the same builtin documents (P-001 acceptance).

Runs BOTH pipelines' full generation chains (the GUI handlers' order, minus the document-mutating
legs: no IF_-sheet insert, no ph200 fill) into isolated sandboxes, then compares:
  - every SSOT table CSV               byte-for-byte
  - every generated output file        byte-for-byte, with ONE sanctioned normalization:
      * the CreationInfo generator comment (`generated by pipeline4` vs `pipeline5`)
      * .xlsx compared by CONTENT (cells per sheet) - zip containers are not byte-stable
The verdict is the EXIT CODE (0 = parity): the policy lives in the command, not in log prose.

Run:  .venv/Scripts/python.exe scripts/parity_vs_pl4.py
"""
from __future__ import annotations

import os
import re
import sys
import tempfile

HERE = os.path.dirname(os.path.abspath(__file__))
PL5_ROOT = os.path.dirname(HERE)
REPO = os.path.dirname(PL5_ROOT)
PL4_ROOT = os.path.join(REPO, "Pipeline4App")
sys.path.insert(0, PL5_ROOT)
sys.path.insert(0, PL4_ROOT)



def run_pl4(db_dir: str, out_dir: str) -> None:
    from pipeline4.core import config as c4
    c4._BUILTIN_DATABASE, c4._BUILTIN_OUTPUT = db_dir, out_dir
    from pipeline4.domain import (staging, datablocks, datablock_xml, interfaces, interface_xlsx,
                                  interface_scl, io_tags, diagnosis, diaglist_csv, diagnosis_scl,
                                  hardware, hardware_csv, coverage)
    from pipeline4.domain.blocks import engine
    db, f = staging.stage()
    assert not any(x.severity == "FAIL" for x in f), f"PL4 staging FAIL: {f}"
    db, _ = datablocks.build(db)
    datablock_xml.project(db)
    db, _ = interfaces.build_interfaces(db)
    interface_xlsx.project(db)                       # documentation only; the INSERT leg is skipped
    interface_scl.project(db)
    io_tags.project(db)
    db, _ = diagnosis.build(db)
    diaglist_csv.project(db)
    diagnosis_scl.project(db)
    db, _ = hardware.build(db)
    hardware_csv.project(db)
    db, _ = engine.build(db)
    engine.project(db)
    engine.write_instance_dbs(db)
    db, _ = coverage.build(db)
    coverage.project(db)


def run_pl5(db_dir: str, out_dir: str) -> None:
    from pipeline5.config import paths as p5paths
    p5paths._BUILTIN_DATABASE, p5paths._BUILTIN_OUTPUT = db_dir, out_dir
    from pipeline5.systems.plc_based.siemens_s7.safety.system import SYSTEM
    p5paths.use_system(SYSTEM)
    from pipeline5.phases.staging import iolist as staging
    from pipeline5.phases.datablocks import generator as datablocks
    from pipeline5.systems.plc_based.siemens_s7 import globaldb_xml_emitter as datablock_xml
    from pipeline5.phases.interfaces import builder as interfaces
    from pipeline5.systems.plc_based.siemens_s7 import interface_xlsx_writer as interface_xlsx
    from pipeline5.systems.plc_based.siemens_s7 import interface_scl_emitter as interface_scl
    from pipeline5.systems.plc_based.siemens_s7 import plctags_xlsx_writer as io_tags
    from pipeline5.phases.diagnosis import builder as diagnosis
    from pipeline5.phases.diagnosis import diaglist as diaglist_csv
    from pipeline5.systems.plc_based.siemens_s7.safety import opc_diagnosis_scl as diagnosis_scl
    from pipeline5.systems.plc_based.siemens_s7 import profinet_hardware as hardware
    from pipeline5.systems.plc_based.siemens_s7 import hardware_csv_export as hardware_csv
    from pipeline5.phases.software_blocks import build_engine as engine
    from pipeline5.phases.coverage import coverage
    db, f = staging.stage(system=SYSTEM)
    assert not any(x.severity == "FAIL" for x in f), f"PL5 staging FAIL: {f}"
    db, _ = datablocks.build(db, system=SYSTEM)
    datablock_xml.project(db)
    db, _ = interfaces.build_interfaces(db)
    interface_xlsx.project(db)
    interface_scl.project(db)
    io_tags.project(db)
    db, _ = diagnosis.build(db)
    diaglist_csv.project(db)
    diagnosis_scl.project(db)
    db, _ = hardware.build(db)
    hardware_csv.project(db)
    db, _ = engine.build(db, system=SYSTEM)
    engine.project(db, system=SYSTEM)
    engine.write_instance_dbs(db)
    db, _ = coverage.build(db, system=SYSTEM)
    coverage.project(db, system=SYSTEM)


def _tree(root: str) -> dict:
    out = {}
    for r, _d, files in os.walk(root):
        for f in files:
            p = os.path.join(r, f)
            out[os.path.relpath(p, root).replace(os.sep, "/")] = p
    return out


def _norm_text(data: bytes) -> bytes:
    """The ONE sanctioned normalization on text bytes: the generator `#` comment line."""
    try:
        text = data.decode("utf-8")
    except UnicodeDecodeError:
        return data
    text = re.sub(r"generated by pipeline\d", "generated by pipeline<N>", text)
    return text.encode("utf-8")


def _xlsx_cells(path: str):
    import openpyxl

    def norm(v):
        # ArrayFormula objects compare by identity - reduce to their comparable content
        if v.__class__.__name__ == "ArrayFormula":
            return ("ARRAY", getattr(v, "ref", None), getattr(v, "text", None))
        return v

    wb = openpyxl.load_workbook(path, data_only=False)
    return {ws.title: [[norm(c.value) for c in row] for row in ws.iter_rows()] for ws in wb.worksheets}


def compare(a_root: str, b_root: str, label: str) -> list:
    diffs = []
    a, b = _tree(a_root), _tree(b_root)
    for rel in sorted(set(a) | set(b)):
        if rel not in a:
            diffs.append(f"{label}: PL5-only file {rel}")
            continue
        if rel not in b:
            diffs.append(f"{label}: PL4-only file {rel}")
            continue
        if rel.lower().endswith((".xlsx", ".xlsm")):
            if _xlsx_cells(a[rel]) != _xlsx_cells(b[rel]):
                diffs.append(f"{label}: xlsx content differs: {rel}")
            continue
        da = _norm_text(open(a[rel], "rb").read())
        db = _norm_text(open(b[rel], "rb").read())
        if da != db:
            diffs.append(f"{label}: bytes differ: {rel}")
    return diffs


def main() -> int:
    with tempfile.TemporaryDirectory() as tmp:
        p4db, p4out = os.path.join(tmp, "pl4", "db"), os.path.join(tmp, "pl4", "out")
        p5db, p5out = os.path.join(tmp, "pl5", "db"), os.path.join(tmp, "pl5", "out")
        for d in (p4db, p4out, p5db, p5out):
            os.makedirs(d)
        print("running PL4 (frozen reference)...")
        run_pl4(p4db, p4out)
        print("running PL5...")
        run_pl5(p5db, p5out)
        diffs = compare(p4db, p5db, "SSOT") + compare(p4out, p5out, "OUTPUT")
        print(f"\ncompared {len(_tree(p4db))} SSOT files + {len(_tree(p4out))} output files")
        if diffs:
            print(f"PARITY BROKEN - {len(diffs)} differences:")
            for d in diffs:
                print("  ", d)
            return 1
        print("PARITY OK - 0 diffs (PL4 -> PL5 byte-identical modulo the sanctioned normalizations)")
        return 0


if __name__ == "__main__":
    sys.exit(main())
